{
  "create": {
    "parentObject": {
      "database": "E2E_DQ"
    },
    "table": {
      "name": "E2E tF_comet_dq_table",
      "columns": [
        {
          "name": "eqpno",
          "dataType": "string",
          "sourceColumn": "eqpno"
        },
        {
          "name": "acttim",
          "dataType": "dateTime",
          "sourceColumn": "acttim"
        },
        {
          "name": "acttim_utc",
          "dataType": "dateTime",
          "sourceColumn": "acttim_utc"
        },
        {
          "name": "year",
          "dataType": "int64",
          "sourceColumn": "year"
        },
        {
          "name": "Month_name",
          "dataType": "string",
          "sourceColumn": "Month_name"
        },
        {
          "name": "geosite_cd",
          "dataType": "string",
          "sourceColumn": "geosite_cd"
        },
        {
          "name": "move",
          "dataType": "string",
          "sourceColumn": "move"
        },
        {
          "name": "ffe",
          "dataType": "double",
          "sourceColumn": "ffe"
        },
        {
          "name": "chtim",
          "dataType": "dateTime",
          "sourceColumn": "chtim"
        },
        {
          "name": "etl_load_date",
          "dataType": "dateTime",
          "sourceColumn": "etl_load_date"
        },
        {
          "name": "COUNTRY_NAME",
          "dataType": "string",
          "sourceColumn": "COUNTRY_NAME"
        },
        {
          "name": "LOC_CD",
          "dataType": "string",
          "sourceColumn": "LOC_CD"
        },
        {
          "name": "Week",
          "dataType": "int64",
          "sourceColumn": "Week"
        },
        {
          "name": "empty_units_cnt",
          "dataType": "int64",
          "sourceColumn": "empty_units_cnt"
        },
        {
          "name": "full_units_cnt",
          "dataType": "int64",
          "sourceColumn": "full_units_cnt"
        },
        {
          "name": "live_reefer_units_cnt",
          "dataType": "int64",
          "sourceColumn": "live_reefer_units_cnt"
        },
        {
          "name": "oog_units_cnt",
          "dataType": "int64",
          "sourceColumn": "oog_units_cnt"
        },
        {
          "name": "Hazardous_cnt",
          "dataType": "int64",
          "sourceColumn": "Hazardous_cnt"
        },
        {
          "name": "Hazardous_reefer_cnt",
          "dataType": "int64",
          "sourceColumn": "Hazardous_reefer_cnt"
        },
        {
          "name": "LATENCY",
          "dataType": "double",
          "sourceColumn": "LATENCY"
        },
        {
          "name": "Source_LATENCY",
          "dataType": "double",
          "sourceColumn": "Source_LATENCY"
        },
        {
          "name": "Raw_LATENCY",
          "dataType": "double",
          "sourceColumn": "Raw_LATENCY"
        },
        {
          "name": "date_part",
          "dataType": "dateTime",
          "sourceColumn": "date_part"
        },
        {
          "name": "INSERT_TS",
          "dataType": "dateTime",
          "sourceColumn": "INSERT_TS"
        },
        {
          "type": "calculated",
          "name": "Year_Quarter",
          "dataType": "string",
          "isDataTypeInferred": true,
          "expression": "'E2E tF_comet_dq_table'[year]&\"Q\"&QUARTER('E2E tF_comet_dq_table'[acttim_utc])"
        },
        {
          "type": "calculated",
          "name": "Container_Count",
          "dataType": "int64",
          "isDataTypeInferred": true,
          "expression": "1"
        },
        {
          "type": "calculated",
          "name": "Delayed_hazard_reef_unit",
          "dataType": "int64",
          "isDataTypeInferred": true,
          "expression": "IF(AND('E2E tF_comet_dq_table'[Source_LATENCY]>24,'E2E tF_comet_dq_table'[Hazardous_reefer_cnt]=1),1,0)"
        },
        {
          "type": "calculated",
          "name": "Delayed_hazard_unit",
          "dataType": "int64",
          "isDataTypeInferred": true,
          "expression": "IF(AND('E2E tF_comet_dq_table'[Source_LATENCY]>24,'E2E tF_comet_dq_table'[Hazardous_cnt]=1),1,0)"
        },
        {
          "type": "calculated",
          "name": "Delayed_oog_unit",
          "dataType": "int64",
          "isDataTypeInferred": true,
          "expression": "IF(AND('E2E tF_comet_dq_table'[Source_LATENCY]>24,'E2E tF_comet_dq_table'[oog_units_cnt]=1),1,0)"
        },
        {
          "type": "calculated",
          "name": "Delayed_live_reef_unit",
          "dataType": "int64",
          "isDataTypeInferred": true,
          "expression": "IF(AND('E2E tF_comet_dq_table'[Source_LATENCY]>24,'E2E tF_comet_dq_table'[live_reefer_units_cnt]=1),1,0)"
        },
        {
          "type": "calculated",
          "name": "Delayed_full_unit",
          "dataType": "int64",
          "isDataTypeInferred": true,
          "expression": "IF(AND('E2E tF_comet_dq_table'[Source_LATENCY]>24,'E2E tF_comet_dq_table'[full_units_cnt]=1),1,0)"
        },
        {
          "type": "calculated",
          "name": "Delayed_empty_unit",
          "dataType": "int64",
          "isDataTypeInferred": true,
          "expression": "IF(AND('E2E tF_comet_dq_table'[Source_LATENCY]>24,'E2E tF_comet_dq_table'[empty_units_cnt]=1),1,0)"
        },
        {
          "type": "calculated",
          "name": "Source_delayed_ffe_ind",
          "dataType": "double",
          "isDataTypeInferred": true,
          "expression": "IF('E2E tF_comet_dq_table'[Source_LATENCY]>24,'E2E tF_comet_dq_table'[ffe],0)"
        },
        {
          "type": "calculated",
          "name": "delayed_ffe_ind",
          "dataType": "double",
          "isDataTypeInferred": true,
          "expression": "IF('E2E tF_comet_dq_table'[LATENCY]>24,'E2E tF_comet_dq_table'[ffe],0)"
        },
        {
          "type": "calculated",
          "name": "Raw_Delayed_Container_ind",
          "dataType": "int64",
          "isDataTypeInferred": true,
          "expression": "IF('E2E tF_comet_dq_table'[Raw_LATENCY]>24,1,0)"
        },
        {
          "type": "calculated",
          "name": "Source_delayed_container_ind",
          "dataType": "int64",
          "isDataTypeInferred": true,
          "expression": "IF('E2E tF_comet_dq_table'[Source_LATENCY]>24,1,0)"
        },
        {
          "type": "calculated",
          "name": "Delayed_container_ind",
          "dataType": "int64",
          "isDataTypeInferred": true,
          "expression": "IF('E2E tF_comet_dq_table'[LATENCY]>24,1,0)"
        },
        {
          "type": "calculated",
          "name": "Year_month",
          "dataType": "string",
          "isDataTypeInferred": true,
          "expression": "'E2E tF_comet_dq_table'[year]&'E2E tF_comet_dq_table'[Month_name]"
        },
        {
          "type": "calculated",
          "name": "Year_Week",
          "dataType": "string",
          "isDataTypeInferred": true,
          "expression": "IF('E2E tF_comet_dq_table'[Week]>9,CONCATENATE('E2E tF_comet_dq_table'[year],'E2E tF_comet_dq_table'[Week]),'E2E tF_comet_dq_table'[year]&\"0\"&'E2E tF_comet_dq_table'[Week])"
        }
      ],
      "partitions": [
        {
          "name": "Partition_Last_2_Months",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -2)) and [date_part] <= Date.From(DateTime.LocalNow()))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -2)) and [date_part] <= Date.From(DateTime.LocalNow()))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_2months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -4)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -2)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -4)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -2)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_4months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -6)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -4)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -6)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -4)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_6months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -8)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -6)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -8)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -6)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_8months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -10)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -8)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -10)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -8)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_10months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -12)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -10)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -12)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -10)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_12months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -14)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -12)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -14)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -12)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_14months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -16)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -14)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -16)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -14)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_16months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -18)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -16)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -18)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -16)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_18months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -20)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -18)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -20)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -18)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_20months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -22)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -20)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -22)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -20)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_22months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -24)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -22)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -24)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -22)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_24months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -26)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -24)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -26)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -24)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_26months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -28)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -26)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -28)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -26)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_28months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -30)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -28)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -30)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -28)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_30months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -32)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -30)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -32)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -30)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_32months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -34)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -32)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -34)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -32)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "2Months_before_last_34months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -36)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -34)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -36)) and [date_part] < Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -34)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        },
        {
          "name": "Months_Before_last_36months",
          "mode": "import",
          "source": {
            "type": "m",
            "expression": [
              "let",
              "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
              "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
              "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] <= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -36)))",
              "in",
              "    #\"Filtered Rows\""
            ]
          },
          "annotations": [
            {
              "name": "QueryEditorSerialization",
              "value": [
                "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                "    Source = #\"SQL/eval-opse2e-platform2-sql-server database windows net;evalopse2eplatform2dw\",",
                "    E2E_tF_comet_dq_table = Source{[Schema=\"E2E\",Item=\"tF_comet_dq_table\"]}[Data],",
                "#\"Filtered Rows\" = Table.SelectRows(E2E_tF_comet_dq_table, each [date_part] <= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -36)))",
                "in",
                "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              ]
            }
          ]
        }
      ],
      "measures": [
        {
          "name": "comet_delayed_containers_sum",
          "expression": "SUM('E2E tF_comet_dq_table'[Delayed_container_ind])"
        },
        {
          "name": "comet_Source_delayed_containers_sum",
          "expression": "SUM('E2E tF_comet_dq_table'[Source_delayed_container_ind])"
        },
        {
          "name": "comet_delayed_ffe_sum",
          "expression": "SUM('E2E tF_comet_dq_table'[delayed_ffe_ind])"
        },
        {
          "name": "comet_Source_delayed_ffe_sum",
          "expression": "SUM('E2E tF_comet_dq_table'[Source_delayed_ffe_ind])"
        },
        {
          "name": "comet_total_containers_count",
          "expression": "COUNT('E2E tF_comet_dq_table'[eqpno])"
        },
        {
          "name": "comet_delayed_empty_containers_sum",
          "expression": "SUM('E2E tF_comet_dq_table'[Delayed_empty_unit])"
        },
        {
          "name": "comet_delayed_full_containers_sum",
          "expression": "SUM('E2E tF_comet_dq_table'[Delayed_full_unit])"
        },
        {
          "name": "comet_delayed_lv_containers_sum",
          "expression": "SUM('E2E tF_comet_dq_table'[Delayed_live_reef_unit])"
        },
        {
          "name": "comet_delayed_oog_containers_sum",
          "expression": "SUM('E2E tF_comet_dq_table'[Delayed_oog_unit])"
        },
        {
          "name": "comet_delayed_hazard_containers_sum",
          "expression": "SUM('E2E tF_comet_dq_table'[Delayed_hazard_unit])"
        },
        {
          "name": "comet_delayed_hazardreef_containers_sum",
          "expression": "SUM('E2E tF_comet_dq_table'[Delayed_hazard_reef_unit])"
        },
        {
          "name": "comet_Delayed_percent",
          "expression": "[comet_delayed_containers_sum]/[comet_total_containers_count]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_Completeness_percent",
          "expression": "1-[comet_Delayed_percent]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_Source_Delayed_percent",
          "expression": "[comet_Source_delayed_containers_sum]/[comet_total_containers_count]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_ffe_total",
          "expression": "SUM('E2E tF_comet_dq_table'[ffe])"
        },
        {
          "name": "comet_Delayed_ffe_percent",
          "expression": "[comet_delayed_ffe_sum]/[comet_ffe_total]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_Source_Delayed_ffe_percent",
          "expression": "[comet_Source_delayed_ffe_sum]/[comet_ffe_total]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_Empty_Containers_percent",
          "expression": "[comet_delayed_empty_containers_sum]/[comet_total_containers_count]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_Full_Containers_percent",
          "expression": "[comet_delayed_full_containers_sum]/[comet_total_containers_count]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_Livereefer_Containers_percent",
          "expression": "[comet_delayed_lv_containers_sum]/[comet_total_containers_count]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_oog_Containers_percent",
          "expression": "[comet_delayed_oog_containers_sum]/[comet_total_containers_count]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_Hazard_Containers_percent",
          "expression": "[comet_delayed_hazard_containers_sum]/[comet_total_containers_count]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_Hazardreefer_Containers_percent",
          "expression": "[comet_delayed_hazardreef_containers_sum]/[comet_total_containers_count]",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_average_latency",
          "expression": "AVERAGE('E2E tF_comet_dq_table'[LATENCY])",
          "formatString": "0.00"
        },
        {
          "name": "comet_average_source_latency",
          "expression": "AVERAGE('E2E tF_comet_dq_table'[Source_LATENCY])",
          "formatString": "0.00"
        },
        {
          "name": "comet_Latency_percentile",
          "expression": "PERCENTILE.EXC('E2E tF_comet_dq_table'[LATENCY],0.95)"
        },
        {
          "name": "comet_Source_Latency_percentile",
          "expression": "PERCENTILE.EXC('E2E tF_comet_dq_table'[Source_LATENCY],0.95)"
        },
        {
          "name": "comet_95th% Raw Percentile",
          "expression": "PERCENTILE.EXC('E2E tF_comet_dq_table'[Raw_LATENCY],0.95)"
        },
        {
          "name": "comet_Average Raw Latency",
          "expression": "AVERAGE('E2E tF_comet_dq_table'[Raw_LATENCY])"
        },
        {
          "name": "comet_delayed_containers%_LOC",
          "expression": "DIVIDE(SUM('E2E tF_comet_dq_table'[Delayed_container_ind]),CALCULATE(SUM('E2E tF_comet_dq_table'[Container_Count]),ALL('E2E tF_comet_dq_table'[LOC_CD])))"
        },
        {
          "name": "comet_avg_completeness_last_8W%",
          "expression": "var week = WEEKNUM(TODAY(),21) return 1- CALCULATE(DIVIDE(SUMX('E2E tF_comet_dq_table',[comet_delayed_containers_sum]),SUMX('E2E tF_comet_dq_table',[comet_total_containers_count])), 'E2E tF_comet_dq_table'[Week]>=week &&'E2E tF_comet_dq_table'[Week]<=WEEKNUM(TODAY(),1),'E2E tF_rkem_dq_table'[year] = YEAR(TODAY()))",
          "formatString": "0.00%;-0.00%;0.00%"
        },
        {
          "name": "comet_avg_adls_latency_last_8W",
          "expression": [
            " ",
            "var week = WEEKNUM(TODAY(),21) - 8",
            "return CALCULATE(AVERAGE('E2E tF_comet_dq_table'[LATENCY]),'E2E tF_comet_dq_table'[Week]>= week && 'E2E tF_comet_dq_table'[Week]<=WEEKNUM(TODAY(),21),'E2E tF_rkem_dq_table'[year] = YEAR(TODAY()))"
          ]
        },
        {
          "name": "comet_avg_source_latency_last_8W",
          "expression": [
            " ",
            "var week = WEEKNUM(TODAY(),21) - 8",
            "return CALCULATE(AVERAGE('E2E tF_comet_dq_table'[Source_LATENCY]),'E2E tF_comet_dq_table'[Week]>= week && 'E2E tF_comet_dq_table'[Week]<=WEEKNUM(TODAY(),21),'E2E tF_rkem_dq_table'[year] = YEAR(TODAY()))"
          ]
        }
      ]
    }
  }
}

